safe:        false
port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     [hwc_jekyll_site.iml, helsinkiwindsurfingclub.fi.iml, Gemfile, Gemfile.lock, README.md, deploy.sh]
include:     [.htaccess]

markdown:    kramdown
permalink:   date
